<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">

<head>
<title>ECGSIM: Introduction</title>
<!--META TAGS-->
<meta http-equiv="Content-type" content="text/html; charset=iso-8859-15">
<meta name="description" content="">
<meta name="keywords" content="">
<!--FAVICON-->
<link rel="shortcut icon" href="favicon.ico">
<!--lINK TO EXTERNAL STYLE SHEET-->
<link rel="stylesheet" type="text/css" href="stylesheet.css">
</head>

<body>

<!--START LAYOUT DIV-->
<div class="layout">

<!--START LOGOTYPE MET LINK NAAR HOMEPAGE-->
<a name="top"></a><a href="index.php"><img src="graphics/hartlogotype-new-775.png" id="logo" alt="To the Homepage" title="To the Homepage"></a>
<!--END LOGOTYPE-->
<p>
<!--START HEADERBAR-->
<!-- DE HEADERBAR IS HET BOVENSTE HORIZONTALE NAVIGATIEMENU -->
<div class="headerbar">

<a href='index.php'>HOME</a><img src='graphics/whitespace.png' class='whitepace-navigationbar' alt=''>INTRODUCTION<img src='graphics/whitespace.png' class='whitepace-navigationbar' alt=''><a href='downloads/'>DOWNLOADS</a><img src='graphics/whitespace.png' class='whitepace-navigationbar' alt=''><a href='manual/'>MANUAL</a><img src='graphics/whitespace.png' class='whitepace-navigationbar' alt=''><a href='aboutus.php'>ABOUT&nbsp;US</a>
</div>
<!--END HEADERBAR-->
<p>
<!--START TEXT-->
<!-- het volgende script moet 1 keer worden aangeroepen -->
<script src="hik.js" language="javascript" type="text/javascript"></script>

<p class="text">
ECGSIM is an interactive simulation program that enables one to
study the relationship between the electric activity of the 
myocardium and the resulting potentials on the thorax: PQRST wave forms as
well as body surface potential maps.
</p>

<h2>Education</h2>
<p class="text">
One of the purposes of ECGSIM is to serve as a teaching tool for
students of the basic aspects of electrocardiography. In a typical
setting students use ECGSIM in a lab class environment.
Following instructions, they change the electric activity of the heart
and observe the effect on the ECG. Example instructions may be
downloaded from the <a href="downloads"> download area</a>.
</p>

<h2>Research</h2>
<p class="text">	
ECGSIM is also used as a research tool
for those that are interested to test any hypothesis they may have
regarding the manifestation of cardiac malfunctioning in
the electrocardiographic wave forms on the thorax.
</p>

<p class="text">
<b>Please note:</b> Any diagnostic application is only indirect; ECGSIM
provides a forward simulation and does not solve the inverse problem.
</p>

<h2>Basis usage</h2>
<p class="text">
ECGSIM's main windows consists of several panes. One of them displays
the heart, together with a map of the depolarization times,
repolarization times or transmembrane potential amplitude at the
heart. The user may change these parameters, and observe in the other
panes the effect of these changes on the ECG and the potential at the
body surface. 
</p>

<img src="manual/graphics/ecgsim_initial.png" alt="Screen dump of the ECGSIM main window" title="Screen dump of the ECGSIM main window" style="width:790px;height:454px;">

<p class="text">
In an educational setting users change the electric activity in
regions of the heart to simulate defects like local ischemia, bundle
branch blocks, hypertrophy and ectopic foci. Observing the effect on
the ECG will help the students to understand the relation between the
activity of the heart and its expression in the ECG.
</p>

<h2>Underlying model</h2>
<p class="text">
ECGSIM is based on the equivalent surface source model, which states
that the electric potentials at the body surface generated by the
heart are determined completely by the transmembrane potentials at the
surface bounding the active region (the myocardium). Hence,
ECGSIM uses the waveform of the transmembrane potential at the surface
consisting of the epicardium, endocardium and AV-ring as the source
model. The atria and ventricles are represented by separate surfaces.
In the most common application, the waveform is parameterized by the
depolarization time, the repolarization time and the transmembrane
amplitude.
</p>

<p class="text">
The geometry of the heart, and that of the structures that represent
regions of different electric conductivity, were determined from MR
images. From this a volume conductor model was constructed. The
boundary element model was used to compute the transfer function that
describes the relation between the transmembrane potentials at the
surface of the myocardium and the potentials at the body surface,
based on the laws of current flow in an inhomogeneous medium.
</p>

<p class="text">
The depolarization and repolarization times were estimated from
measured ECGs using an inverse procedure (see <a
href="manual/ref.php">references</a>). These are the default
parameters that are used in ECGSIM. The user can change these
parameters, and ECGSIM uses the transfer function
to compute the resulting ECGs.
</p>

<p class="text">		  
More details of the theory behind ECGSIM can be found in the papers
listed in the <a href="manual/ref.php">reference</a> list.
</p>

<h2>History</h2>
<p class="text">
The theory used has been developed starting in 1972 in a 
collaboration between the department of Medical Physics and the 
department of Cardiology and Clinical Physiology of the University 
of Amsterdam, and has been expanded from 1981 onward at the
<a href= "http://www.ru.nl/mbphysics">Department of Medical Physics 
of the University of Nijmegen</a>, both cities located in the 
Netherlands. The simulation package has had several predecessors. 
The ongoing development has been inspired by the enthusiastic comments 
of the users to which these earlier versions have been made available.
</p>

<h2>Updates and additional material</h2>
<p class="text">
The package is constantly being developed to greater perfection. Recent
updates will be available from <a
 href="http://www.ecgsim.org">www.ecgsim.org</a>.  You can determine
the version you are currently working with by choosing <tt>About
ECGSIM</tt> in the <tt>Help</tt> menu. You can also use the 
<a href="manual/update.php#ECGsimUpdater">update checking tool</a> that 
is part of the installer or use the 
<a href="manual/update.php#UpdateCheck">update checking feature</a> 
build in the application.
</p>

<p class="text">
Additional material, such as specific cases and tutorials, are also
distribution through <a
href="http://www.ecgsim.org">www.ecgsim.org</a>
</p>

<h2>User Input</h2>
<p class="text">
Any comments and suggestions for improvements will be greatly appreciated.
Please send your comments by e-mail to
<script type="text/javascript">hip("org", "info", "ecgsim", "ECGSIM")</script>.
</p>

<!--END TEXT-->
<p>
<!--START FOOTERNAVIGATIONBAR-->
<div class="footerbar">


<a href='index.php'>HOME</a><img src='graphics/whitespace.png' class='whitepace-navigationbar' alt=''><a href='contact.php'>CONTACT&nbsp;US</a><img src='graphics/whitespace.png' class='whitepace-navigationbar' alt=''><a href='#top'>TOP OF THIS PAGE</a>
<!--
<a href="http://validator.w3.org/check?uri=referer" style="float:right;" target="_blank">Valid html4</a>
-->
</div>
<!--END FOOTERNAVIGATIONBARBAR-->

</div>
<!--END LAYOUT DIV-->
</body>
</html>