"""Legacy ECGSIM readers and writers."""

from ecgsim.io.ecgsimcase import (
    ECGsimCaseFormatError,
    ECGsimCase,
    ECGsimCaseActivation,
    ECGsimCaseElectrode,
    ECGsimCaseGeometry,
    ECGsimCaseLeadSystem,
    ECGsimCaseMetadata,
    ECGsimCaseSignalMetadata,
    ECGsimCaseSource,
    ECGsimCaseSourceBeat,
    ECGsimCaseSourceParameter,
    ECGsimCaseVector,
    StringEntry,
    load_case,
    read_ecgsimcase_geometries,
    read_ecgsimcase_lead_systems,
    read_ecgsimcase_matrix,
    read_ecgsimcase_metadata,
    read_ecgsimcase_signal_metadata,
    read_ecgsimcase_sources,
    read_ecgsimcase_vector,
)
from ecgsim.io.geometry import GeometryData, GeometryFormatError, read_geometry
from ecgsim.io.matrix import MatrixData, MatrixFormatError, VectorData, read_matrix, read_vector

__all__ = [
    "ECGsimCaseFormatError",
    "ECGsimCase",
    "ECGsimCaseActivation",
    "ECGsimCaseElectrode",
    "ECGsimCaseGeometry",
    "ECGsimCaseLeadSystem",
    "ECGsimCaseMetadata",
    "ECGsimCaseSignalMetadata",
    "ECGsimCaseSource",
    "ECGsimCaseSourceBeat",
    "ECGsimCaseSourceParameter",
    "ECGsimCaseVector",
    "GeometryData",
    "GeometryFormatError",
    "MatrixData",
    "MatrixFormatError",
    "StringEntry",
    "VectorData",
    "load_case",
    "read_ecgsimcase_geometries",
    "read_ecgsimcase_lead_systems",
    "read_ecgsimcase_matrix",
    "read_ecgsimcase_metadata",
    "read_ecgsimcase_signal_metadata",
    "read_ecgsimcase_sources",
    "read_ecgsimcase_vector",
    "read_geometry",
    "read_matrix",
    "read_vector",
]
